### PR TITLE
todays class

### PR DESCRIPTION
**Pull request by NexusGKSoftwares**

### CODE REVIEW

**Comment by jessec01** [comment]
Hello, this is my first time using GitHub. I would like to do my first collaboration. Anything that can help your project?

**Comment by NexusGKSoftwares** [comment]
Yes let's collaborate which projects do you work on

**Comment by NexusGKSoftwares** [comment]
Which one is your best language you ever learned in the field of coding

**Comment by jessec01** [comment]
Python, Ruby, Java and C.

**Comment by NexusGKSoftwares** [comment]
nice to meet you now lets collaborate in working on projects

**Comment by NexusGKSoftwares** [comment]
https://drive.google.com/file/d/1crDwoUx6qmiW5_SWr-XjPJDQseSAeoPq/view?usp=share_link

**Pull request merged**
